### ISSUE TITLE
Fixing Content-Type header strict check

### ISSUE THREAD

**Issue by horodchukanton** [fescobar/allure-docker-service#101]
The value for the 'Content-Type' is checked too strict.

https://github.com/fescobar/allure-docker-service/pull/100

**Comment by fescobar** [comment]
@horodchukanton thanks for your contribution. I will test it and when is ready I will release it.
Thanks again.

**Comment by fescobar** [comment]
Aiming PR to `beta` branch
https://github.com/fescobar/allure-docker-service/pull/102

**Comment by fescobar** [comment]
@horodchukanton you had a typo with the name of the method
Instead of
```
startsWith(...
```
should be
```
startswith(..
```
I've already fixed in `beta` branch
https://github.com/fescobar/allure-docker-service/commit/c9e98a9514a649a010acdf98b41e9be634934c7a

**Comment by fescobar** [comment]
@horodchukanton I've re-released version `2.13.4` (remove a previous `2.13.4` image locally if you had one).
Thank you for your contribution.
https://github.com/fescobar/allure-docker-service/releases/tag/v2.13.4

**Comment by horodchukanton** [comment]
> @horodchukanton you had a typo with the name of the method
> Instead of
> 
> ```
> startsWith(...
> ```
> 
> should be
> 
> ```
> startswith(..
> ```
> 
> I've already fixed in `beta` branch
> [c9e98a9](https://github.com/fescobar/allure-docker-service/commit/c9e98a9514a649a010acdf98b41e9be634934c7a)

Thank you
