### ISSUE TITLE
How to check specified test round result?

### ISSUE THREAD

**Issue by ansonliao** [fescobar/allure-docker-service#109]
I running the allure server docker in multiple projects version, the scenario is:

1.
project id: my-project-id

2. 
Run test with total test cases = 10, and all test cases failed, then publish the `allure-results` directory to allure server by API call (for example, CURL or shell script), and then generate the test report by the API call (by CURL or shell script, etc.).
Then the first report in allure-server is available with URL: 
http://localhost:5050/allure-docker-service/projects/my-project-id/reports/1/index.html#

The report will show all the test cases are failed, it is expected.

3. 
Run the test again that the test cases executed in step 2 that total is 10, and got the test result that all 10 test cases are passed.
Then publish the `allure-results` to allure-server` and generate the report by API, then we will get the second test report:
http://localhost:5050/allure-docker-service/projects/my-project-id/reports/2/index.html#

Then open the second report, 
Expect:
the report displaying of this round's test information should be shown all test cases are passed.
Actually:
the report displays the testing information is aggregative testing information from all history report, so the report display failed cases that aggregate from the report history that did by step 2.

For example, below it is my the 10th round test report
![image](https://user-images.githubusercontent.com/6060224/88465734-ad6bf980-cef7-11ea-8d4a-960121436077.png)

the report list many test case failures and others passes.

actually, in the 10th round of the testing, only one test case executed and failed, the test case is below:
![image](https://user-images.githubusercontent.com/6060224/88465756-f328c200-cef7-11ea-9da1-98920674eb02.png)

when I open this test round's report: http://192.168.1.80:5050/allure-docker-service/projects/my-project-id/reports/10/index.html#suites
I only care which test case failed in this round of test (`melco.limo.LimoBookingDailyLimitTest
#testADTFeatureForPatron`), I don't care other round's test failed and passed (`melco.limo.LimoBookingDailyLimitTest#afterMethod`, actually this failed case happened in the 1st test round, fixed already), I only care about this test round's test result (pass and fail, most focus on failure).

would like to know is it possible to only display the single history report without aggregation? the url is: http://localhost:5050/allure-docker-service/projects/[project_id]reports/[history_id]/index.html#

and then the latest report of the project displays the aggregation of the test report history:
http://localhost:5050/allure-docker-service/projects/[project_id]reports/latest/index.html#

I know we can check the test case history from the tab `History` in the test case detail, but it is hard to debug when my current test has some test case failed to need to check the failure details.

Thanks.

**Comment by fescobar** [comment]
@ansonliao did you try using `CHECK_RESULTS_EVERY_SECONDS: NONE` and `GET /clean-results` before request `GET /generate-report`?

**Comment by ansonliao** [comment]
@fescobar , I tried `GET /clean-results` and `CHECK_RESULTS_EVERY_SECONDS: NONE`, it works in my expectation, thanks for your help.

**Comment by fescobar** [comment]
I've released a fix in version `2.13.5`  of your interest https://github.com/fescobar/allure-docker-service/issues/110

**Comment by ansonliao** [comment]
@fescobar thanks for your update and I will try later
