### ISSUE TITLE
15/Aug/2020 05:39:54] \"GET / HTTP/1.1\" 303 - 14 0.028 0.304\n"

### ISSUE THREAD

**Issue by ivanruiz03** [fescobar/allure-docker-service#117]
hola que tal. 
estoy haciendo un deployment de odoo en un cluster de kubernetes, y veo que en el log aparece la comprobación de estado 303. 
15/Aug/2020 05:39:54] \"GET / HTTP/1.1\" 303 - 14 0.028 0.304\n"
 que es lo que tengo que hacer para que me resuelva con un estado 200? 
si yo configuro un LB sobre este workload, este si responde OK!, pero si lo quiero hacer con un "nodeport" el pods en el que esta corriendo resuelve con un estado HTTP 303, en lugar de un HTTP 200: 
root@server01: curl -i 10.40.0.20:8069
### HTTP/1.0 303 SEE OTHER
Content-Type: text/html; charset=utf-8
Content-Length: 215
Location: http://10.40.0.20:8069/web
Set-Cookie: session_id=81d12c47a0c23032c346cdb9fc1f05dd8ca1bca1; Expires=Fri, 13-Nov-2020 05:05:26 GMT; Max-Age=7776000; HttpOnly; Path=/
Server: Werkzeug/0.14.1 Python/3.7.3
Date: Sat, 15 Aug 2020 05:05:26 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="/web">/web</a>.  If not click the link

**Comment by fescobar** [comment]
@ivanruiz03 can you share the kubernetes configuration? Or env variables that you are setting? what endpoint are you using?
In general please can you add more details?
Thanks

**Comment by ivanruiz03** [comment]
@fescobar no, estoy siguiendo esa guía 
Instalé una imagen con los archivos que baje de esta guia: 
https://github.com/odoo/docker/tree/master/13.0

y este fue el proceso que ejecuté: 
1.- docker build -t odoo:1.0 .   --> contruí la imagen
2.- docker run -d --name odoo odoo:1.0   -->  la ejecuté 
3.- gcloud builds submit --tag gcr.io/odoo20/odoo:0.1   --> y la metí a este contenedor que deploye en un cluster de Kubernete.

una vez que tuve la imagen creada, hice el deploy en un cluster de Kubernetes
el cluster no tiene tiene mucha configuración solo le puse la imagen a deployar, en este caso lo configuré con 1 solo nodo: 

para deployar la imagen del paso #3 
![image](https://user-images.githubusercontent.com/69708431/90317211-5b623680-deed-11ea-8d5b-94de3a488eb4.png)

ejecute deploy y listo: ya tengo el cluster con 1 nodo y 3 replicas en kubernetes
![image](https://user-images.githubusercontent.com/69708431/90317233-7e8ce600-deed-11ea-8886-a15e0f334bb6.png)

y este es el yaml que me genera el deploy de la imagen: 
odoo-rola.yaml (adjunto archivo
[odoo-rola.yaml.txt](https://github.com/fescobar/allure-docker-service/files/5079170/odoo-rola.yaml.txt)
)

y el error que tengo es que en uno de los pods que tengo corriendo este contenedor no responde con estatus HTTP200. 

![image](https://user-images.githubusercontent.com/69708431/90317380-ac265f00-deee-11ea-946e-3036f573bac9.png)

y por lo tanto es aquí donde no tengo idea como hacerle para que el pods me regrese un estado 200 en lugar del 303. 

gracias por tus comentarios. 

Saludos

**Comment by fescobar** [comment]
@ivanruiz03 the info specified for you, it's not related to Allure Docker container. I think you should ask or create an issue in this repository: https://github.com/odoo/docker/issues
