### ISSUE TITLE
Optimization of storage

### ISSUE THREAD

**Issue by VojKozel** [fescobar/allure-docker-service#126]
Current solution wasting too much disk storage because of copy-pasting all content via 

cp --recursive --preserve=timestamps $PROJECT_LATEST_REPORT/* $NEW_REPORT_DIRECTORY/

For default allure server configurations, files like app.js, styles.css etc.. are absolutely the same and for each report, they take about 2-3MB+. From the perspective where we want to use this server for some automated test which runs multiple times per day, it can waste a lot of storage for no reason. 

There should be added some experimental feature (Idk how about all allure server configuration, where these files should be different, but for default allure report from cucumber test it's ok) where it will replace copy-pasting of all files by creating symlinks. 

I mean something like 

`ln -s $PROJECT_LATEST_REPORT/styles.css $NEW_REPORT_DIRECTORY/styles.css`
`ln -s $PROJECT_LATEST_REPORT/app.js $NEW_REPORT_DIRECTORY/app.js`

It will be great if you will think about this feature, it should helpful everyone who wants to use your image for real usage.

**Comment by fescobar** [comment]
Thank you @VojKozel. This will be the next improvement.

**Comment by AdamRussak** [comment]
@fescobar  when will this be implemented ?
we are using the image and our storage is getting full with only 40 tests (150GB)

**Comment by fescobar** [comment]
@AdamRussak don't use CHECK_RESULTS_EVERY_SECONDS:3 for multiprojects. That is going to generate thousands reports. Use CHECK_RESULTS_EVERY_SECONDS: NONE instead. Use the GET /generate-report endpoint once you have all the results files generate. On that way, only you will generate just one report on demand.
I will continue developing the next year.

**Comment by fescobar** [comment]
@VojKozel @AdamRussak you will have news soon.

**Comment by fescobar** [comment]
@VojKozel @AdamRussak 
The version `2.13.7` was released with the improvement suggested
https://github.com/fescobar/allure-docker-service/releases/tag/v2.13.7

The documentation about that is here:
https://github.com/fescobar/allure-docker-service#optimize-storage

Thank you for your suggestions

**Comment by AdamRussak** [comment]
@fescobar  appreciate it!
Updated and checking!
