### ISSUE TITLE
413 Response Code on sending results

### ISSUE THREAD

**Issue by AAAver** [fescobar/allure-docker-service#127]
Happens if you use NGINX as reverse-proxy.
You could fix it with  setting up the limit of nginx.ingress.kubernetes.io/proxy-body-size

https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-kubernetes-example/allure-ingress-service-load-balancer.yml#L8

**Comment by fescobar** [comment]
@AAAver if you are using NGINX without Kubernetes you can try this one: https://stackoverflow.com/a/28476755/10299604

**Comment by greysky007** [comment]
> [@AAAver](https://github.com/AAAver) if you are using NGINX without Kubernetes you can try this one:
> 
> * https://stackoverflow.com/a/28476755/10299604
> * http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

And if I dont use nginx? I have this messge when sending result {"meta_data":{"message":"413 Request Entity Too Large: The data value transmitted exceeds the capacity limit."}}. Please help!

**Comment by fescobar** [comment]
@greysky007 I think you have a different load balancer controling the size of the data.

**Comment by Moramuy** [comment]
Hey, we ran into this issue sending a result with 1060 weighing 170 MB. Apparently there is a cap of sending 1000 files each time. So we send 999 and it seems to do the trick
