### ISSUE TITLE
Add role admin/viewer

### ISSUE THREAD

**Issue by fescobar** [fescobar/allure-docker-service#128]
Add new roles to differentiate views.
Related to https://github.com/fescobar/allure-docker-service-ui/issues/6

**Comment by fescobar** [comment]
@nodlesh FYI

**Comment by fescobar** [comment]
@nodlesh
This feature was released!

To see reflected the new feature `Admin/Viewer roles`  use any version of API container from `2.13.7` and use any version of UI container from `7.0.1`

**allure-docker-service (API)**
https://github.com/fescobar/allure-docker-service/releases/tag/v2.13.7

**allure-docker-service (UI)**
https://github.com/fescobar/allure-docker-service-ui/releases/tag/v7.0.1

Thank you for your suggestions.

**Comment by nodlesh** [comment]
Does this enhancement allow for no security on the HTML reports? I want to secure the Admin and the API, but not the reports themselves. From reading the docs it seems like the viewer role still needs a username and password. My usecase is to let the public see the reports with no barriers to entry. Thanks.

**Comment by fescobar** [comment]
@nodlesh if you enable security I need to protect the endpoints. For that reason, you need to login as a viewer user. 

I could add a way to disable that and let you access directly to reports. Let me think about that and I will create another ticket.
Thank you.

**Comment by nodlesh** [comment]
Thanks.

**Comment by fescobar** [comment]
@nodlesh I've created this ticket with your requirement https://github.com/fescobar/allure-docker-service/issues/146
