### ISSUE TITLE
Storage Consumption

### ISSUE THREAD

**Issue by AdamRussak** [fescobar/allure-docker-service#129]
we are using your image, but it seems that test runs with a large number of test cases (100+ cases) with IMAGES are using an extreme amount of storage (less than 100MB on test server and 3GB on allure)

we are using your Python script to copy the files from the test server (windows) to the alluring image. 
more info:
6202 files
98MB

**Comment by fescobar** [comment]
Hi @AdamRussak 
That improvement is the backlog. I will implement that soon.
https://github.com/fescobar/allure-docker-service/issues/126
