### ISSUE TITLE
API end point for results

### ISSUE THREAD

**Issue by AnpooSivanadi-okta** [fescobar/allure-docker-service#130]
API end point for the results (Pass/Fail/Broken)

can help us to integrate with other communication channels like 

1.  Slack
2. HipChat
etc

**Comment by fescobar** [comment]
Hi @AnpooSivanadi-okta. Can you give me more technical details? or describe how will you implement that?

**Comment by fescobar** [comment]
@AnpooSivanadi-okta any update about this?

**Comment by fescobar** [comment]
Closing, not answer from a long time.
