### ISSUE TITLE
Network Issue due to Cors policy

### ISSUE THREAD

**Issue by Tonicku** [fescobar/allure-docker-service#131]
"Network Error"
Check if you have access to http://mgs-qa-harbor201.be.monster.com:5050/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)
{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at e.exports (http://mgs-qa-harbor201.be.monster.com:5252/static/js/2.305ecc37.chunk.js:2:69537)\n at XMLHttpRequest.p.onerror (http://mgs-qa-harbor201.be.monster.com:5252/static/js/2.305ecc37.chunk.js:2:68488)","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*","X-XSRF-TOKEN":"818dojrlpjhge5qrugc4uhl27h"},"baseURL":"http://mgs-qa-harbor201.be.monster.com:5050/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"withCredentials":true}}

WebTool - Console
Access to XMLHttpRequest at 'http://mgs-qa-harbor201.be.monster.com:5050/allure-docker-service/config' from origin 'http://mgs-qa-harbor201.be.monster.com:5252' has been blocked by CORS policy: Request header field x-xsrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by fescobar** [comment]
Hi @Tonicku can you use the same domain for both containers?
I mean you can use http://mgs-qa-harbor201.be.monster.com/allure-docker-service and http://mgs-qa-harbor201.be.monster.com/allure-docker-service-ui (using the same domain without ports)
To store the credentials in the browsers is necessary to use the same domain.

**Comment by Tonicku** [comment]
> Hi @Tonicku can you use the same domain for both containers?
> I mean you can use http://mgs-qa-harbor201.be.monster.com/allure-docker-service and http://mgs-qa-harbor201.be.monster.com/allure-docker-service-ui (using the same domain without ports)
> To store the credentials in the browsers is necessary to use the same domain.

hi @fescobar,
Yes i am using the same domain
That behavior was not occuring on Chrome then when i get back i could see this message CORS error.
That behavior doesn't occur when i am not on Chrome. It was ok with Opera or Firefox
My colleague is able to open on Chrome without having this CORS issue

**Comment by fescobar** [comment]
@Tonicku it should be the chrome version? can you tell me what version of chrome is failing? Thank you

**Comment by Tonicku** [comment]
@fescobar here is the version i am using
Version 86.0.4240.111 (Official Build) (64-bit)
