### ISSUE TITLE
Multiple projects search for results path as "results" and not "allure-results"

### ISSUE THREAD

**Issue by hananmalka** [fescobar/allure-docker-service#132]
When I'm trying to get the report via allure-docker-service-ui, It search for it in the path /app/projects/MY_PROJECT_ID/**results**

While I'm mapping local projects dir where the results are in **allure-results**

I'm getting an error that path are not exists for /app/projects/MY_PROJECT_ID/**results**

I tried to rename the output directory to be "results" but didn't manage to do it (using jest-allure)

Does anyone can help what am I doing wrong?

**Comment by fescobar** [comment]
Hi @hananmalka 
I don't understand your point. Can you add more details like docker configuration, API requests, etc?

**Comment by fescobar** [comment]
@hananmalka From the UI, you don't need to put any path, just you need to put the name of your project.

You have 2 ways to attach your volumes. One is for local projects and another one for multiprojects.

1. Local project: https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-java-cucumber-jvm-example/docker-compose.yml

```sh
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
```
On the left side, you have to put any local directory from your machine.
On the right side, you don't need to change anything. That is internal to the docker container.


2. Multi project https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-multi-project-example/docker-compose.yml

```sh
    volumes:
      - ${PWD}/projects:/app/projects
```
On the left side, you have to put any local directory from your machine. In there you will store all reports from all your projects.
On the right side, you don't need to change anything. That is internal to the docker container.

Follow the examples and documentation.
 

Let me know if you can resolve it. I will close the issue.
