### ISSUE TITLE
Any plan to add the entry dashboard page for multiple projects mode

### ISSUE THREAD

**Issue by ansonliao** [fescobar/allure-docker-service#133]
@fescobar 
Thanks for your great work on providing this awesome tool of `Allure`.
I would like to know, is there any plan to add an entry dashboard page for the multiple projects mode?

For example, `Allure Service` URL is: `http://allure-service.aws-space.com`
I have 5 projects of Allure reports now in the allure service (project A, B, C, D, E).
so when launch: `http://allure-service.aws-space.com`, then I can see an entry page of allure multiple projects, and this page displays the list of the allure report projects.

When I click Project A, then we are negatived to the project A's allure's latest report.
or is there a dropdown menu that can switch the different allure report project?

Thanks.

**Comment by fescobar** [comment]
@ansonliao did you try with https://github.com/fescobar/allure-docker-service-ui ?

**Comment by ansonliao** [comment]
@fescobar 
thanks for your reply, never notice the UI service before, let me try and get back to you soon.

**Comment by ansonliao** [comment]
@fescobar 
we can close this issue, thanks for your support.

**Comment by fescobar** [comment]
@ansonliao you're welcome
