### ISSUE TITLE
Order of test cases in the Emailable Report

### ISSUE THREAD

**Issue by Valon94** [fescobar/allure-docker-service#134]
Would be good if the test cases in the Emailable Report are ordered based on their execution order.

**Comment by fescobar** [comment]
@Valon94 I will try to do it in the next version.

**Comment by fescobar** [comment]
Hi  @Valon94 
Your enhancement was released in version `2.13.6`.
First tests executed, the first test showed in the emailable report.
Thank you so much.

**Comment by Valon94** [comment]
Hi @fescobar

**Comment by Valon94** [comment]
Hi @fescobar , it seems that the executed tests in the available report still aren't being showed in the particular order that they have been executed.

**Comment by fescobar** [comment]
@Valon94 that is the order when the allure result file is generated.

**Comment by Valon94** [comment]
@fescobar the test cases seem to be ordered in the allure-docker-service-ui without a problem, but when it comes to the emailable report the tests aren't ordered accordingly.

**Comment by fescobar** [comment]
@Valon94 are you using the latest version 2..13.8? check the date of allure results files in the allure-results directory. It's taking those date inside of docker container.

**Comment by DeLuca-Agustin** [comment]
@fescobar I'm using the latest version and the emailable-report order seems to be random
