### ISSUE TITLE
Does it makes sense that it takes the container about 10-20 seconds to generate the allure report?

### ISSUE THREAD

**Issue by nusnuson** [fescobar/allure-docker-service#140]
When I run the service after running pytest, it takes it about 10-20 seconds to generate the files and show everything on screen and I need to refresh the page to see the view correctly after the files generation process was completed.

Does it make sense or is it just that my laptop is not fast enough?

P.S
Running on MacBook Pro.

**Comment by fescobar** [comment]
@nusnuson take a few seconds to generate a new report overall if you have multiple files. It's the wat that allure2 works. You can create an issue in the proper repository of allure2 about performance.
