### ISSUE TITLE
API responding with try again later

### ISSUE THREAD

**Issue by Riverlution** [fescobar/allure-docker-service#150]
Hi, thanks for the great work on this, seems to work well for what we need.

However, we occasionally seen to run into issues in our ci process where the api responds that it's busy processing files and we need to try again later. When this happens, it's kinda disruptive and means we then have to manually call the apis later on when we've been told the results couldn't be posted properly. Is it be possible to somehow get the server to queue the work it needs to do rather than outright telling us to come back later?

**Comment by fescobar** [comment]
@Riverlution you are sending multiple requests at the same time to `GET /generate-report`.
I can't allow you to do that, because the Allure native architecture doesn't allow you.

**Comment by Riverlution** [comment]
Thanks for the response, so just a follow up, maybe you have some thoughts? 

So our process at the moment for each test run is

1. Runs some tests, the allure output is generated
2. Clear the project results for the given project (so that we only generate the report based on the results from this test run) 
3. Send the results for the tests ran in step 1
4. Generate the report

Often another test run will run directly after for a different allure project. The process is the same as above, but depending on how quick the tests finish, we sometimes get this issue on either step 2 or step 4, because the server is still busy. We tried adding logic to retry the failed request after a little while, but we found that this resulted in multiple reports being created over the same set of data (it told us to try again later, but it seems it actually generated the report anyway in some cases). 

Do you have any recommendations on how we could change this process to work for us? Or is this just a limitation that we have to live with?

**Comment by fescobar** [comment]
@Riverlution you need to disable the automatic generation report and start using different projects. I know it's a bit annoying but the Allure native doesn't allow me to anything else.
