### ISSUE TITLE
Allow us to have nested projects or subfolders by environment/executor

### ISSUE THREAD

**Issue by Phlegethonyarre** [fescobar/allure-docker-service#151]
It would be awesome to be able to separate reports by browser / OS / etc into "subprojects" within one project.
Is it even possible in the current structure of project?

**Comment by fescobar** [comment]
@Phlegethonyarre sorry. Allure2 structure doesn't allow me to do that kind of change. I'm limited.

**Comment by Phlegethonyarre** [comment]
@fescobar thanks for fast reply. Will ask devs about similar future, hope get lucky.
And thanks for your allure service, it's really awesome project!
