### ISSUE TITLE
Swagger can authorise on backend even when security on

### ISSUE THREAD

**Issue by yhrabovskyinomi** [fescobar/allure-docker-service#153]
Secured UI and allure backend are good, but why swagger (opened to world) can easily generate cookie on it own? Is there any possibility  to add login page to swagger? or disable swagger at all? because all auth staff not making any sense if swagger publicly available

**Comment by yhrabovskyinomi** [comment]
Nvm, seems i was having some bugs with cookies. I have no idea but today swagger not allowing to execute any calls against backend without auth.

**Comment by fescobar** [comment]
@yhrabovskyinomi if you enabled the security, you can't use the API if you are not logged correctly. You can't generate a new token if you don't know the credentials.
