### ISSUE TITLE
For multiple projects support, Allure Reports are taking longer for getting generated.

### ISSUE THREAD

**Issue by neha9700199** [fescobar/allure-docker-service#156]
Hey ! I was using the multiple project support feature for Allure server. as this is working fine, the reports for each project is taking very long for getting generated. we are using Ec2 instance having size t3.medium. Please help me with this issue.

**Comment by fescobar** [comment]
@neha9700199 if you want to use it as a server for multiple reports you need to disable the automatic report generation `CHECK_RESULTS_EVERY_SECONDS: NONE`, otherwise, it will take a long time to generate those reports. Use the API to generate the report on demand. Check the NOTE in the readme about multiple projects https://github.com/fescobar/allure-docker-service#multiple-projects---remote-reports

**Comment by neha9700199** [comment]
hey @fescobar thanks for replying. I did Marked CHECK_RESULTS_EVERY_SECONDS: NONE but still it is taking longer to generate reports for every project.

**Comment by fescobar** [comment]
@neha9700199 I need more details to see that. How many projects? are they generating the reports at the same time? what is slow?. The same that behavior is from the native Allure framework. I can't do anything else to improve that.

**Comment by neha9700199** [comment]
@fescobar yes so currently we have 5 projects and they are not generating reports at the same time. the moment I click on the generate-report tab after entering the project-id it is taking time to generate reports.

**Comment by fescobar** [comment]
@neha9700199 you need to check how many results files you are handling per project? you have to clean results before generating a new report. Show the logs at least.

**Comment by neha9700199** [comment]
@fescobar we have currently 22 files in a result folder. I don't have any logs. the response time is very slow.

**Comment by fescobar** [comment]
@neha9700199 I can't help you without any evidence. Check with the person who is configuring that.
