### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by jsa34** [fescobar/allure-docker-service#162]
Issue:  Uploading report data and generating report including video displays video content as present and with correct file size, but video player fails to play video.

![image](https://user-images.githubusercontent.com/31512041/126010781-26c3ef38-4c53-4fa2-86a4-d17b8022369d.png)

**Comment by jsa34** [comment]
Apologies - this may belong in the UI project as I am using that to view the reports

**Comment by fescobar** [comment]
@jsa34 that is related to Allure native report. Seems to be you are not generating the video in the right way. Can you open the video individually in a video player? how are you generating the video? can you share the code?

**Comment by jsa34** [comment]
Apologies - You are absolutely right....

I assumed because:
a) The video file in the allure dir opens successfully,
b) The report contained the correct video size,

That the issue was in the rendering/embedded video player.
However, I have just served the same report locally and getting the same issue.

I will have a look - apologies for taking your time!

**Comment by fescobar** [comment]
@jsa34 you can check how to attach the video here there are some examples with different technologies
https://github.com/fescobar/allure-docker-service-examples

**Comment by jsa34** [comment]
Yes - I have done this, and it appears to be as the example describes, but not functioning as expecting (clearly I could have made a mistake!)

I am generating a report on Allure repo with all the details including the allure result dir generated - if you have any ideas, I would be very happy as this is my first time trying to use Allure with Python and with video - only ever used with Java previously...

https://github.com/allure-framework/allure2/issues/1358
