### ISSUE TITLE
cannot connect to localhost:5050 in openshift while running reports

### ISSUE THREAD

**Issue by sayantandas** [fescobar/allure-docker-service#163]
Hi,
I've successfully deployed docker containers in Openshift 3.11. I'm able to login and view the default project and create a new project using curl command + access token. I'm however, not able to generate the reports. Below is the output

```

Not checking results automatically
--
| ALLURE_VERSION: 2.13.6
| Opening existing report
| [INFO] /app/allure-docker-api/app.py:118 Enabling TLS=1
| [INFO] /app/allure-docker-api/app.py:132 Setting URL_PREFIX=/allure-ui
| [INFO] /app/allure-docker-api/app.py:140 Setting SECURITY_USER
| [INFO] /app/allure-docker-api/app.py:146 Setting SECURITY_PASS
| [INFO] /app/allure-docker-api/app.py:154 Enabling Security Login. SECURITY_ENABLED=1
| 2021-07-28 19:31:58.451:INFO::main: Logging initialized @1557ms to org.eclipse.jetty.util.log.StdErrLog
| Creating history on results directory for PROJECT_ID: default ...
| Copying history from previous results...
| Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
| Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
| Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
| Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
| Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
| Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
| Timeout requesting after 7 attempts

```
my routes are exposed using https
```
ALLURE_DOCKER_PUBLIC_API_URL = https://allure-service-api-myserver.com
URL_PREFIX = allure-ui
```

<div><div style="font-family :  Verdana,  Arial,  Helvetica,  sans-serif; font-size :  10pt;">

Route / Node Port |   | Service Port |   | Target Port | Hostname | TLS Termination
-- | -- | -- | -- | -- | -- | --
allure-service-api / 31141 |   | 6060/TCP (allure-api) |   | 5050 | https://allure-service-api-myserver.com | Edge
allure-service-ui / 32025 |   | 7070/TCP (allure-ui) |   | 5252 | https://allure-service-ui-myserver.com | Edge

</div></div>

The following URLs are accessible when the containers are up and running

UI
https://allure-service-ui-myserver.com/allure-ui/allure-docker-service-ui/signin

api 

https://allure-service-api-myserver.com/allure-ui/allure-docker-service/swagger/

**Comment by fescobar** [comment]
@sayantandas Allure Docker Service restricts the use of cookies from the same domain. API/UI should be deployed under the same domain.
