### ISSUE TITLE
Latest report not working?

### ISSUE THREAD

**Issue by zenmaster24** [fescobar/allure-docker-service#165]
Hi,

I am consuming an allure-docker-service running on kubernetes managed by another team - I can successfully upload results and see my generated report from the link provided, however it is my understanding that I should be able to hit `<server>/allure-docker-service/projects/<project_id>/reports/latest/index.html?redirect=false` to get the latest report, is that correct? If I try, I get trending data, but not the latest report - test cases show as 0 and a NaN% for passing.

I have access to the container if necessary, but was wondering what to look for, or what could be wrong? If this is an indicator, while I can create the project successfully, the `results` directory is never created, only `reports` - `results` needs to be created manually in the container for some reason.

Unsure what version of Allure is being used - if you would like this information, how would I find it?

Thanks

**Comment by fescobar** [comment]
@zenmaster24 check the project directory located in the volume that you are specifying in the Kubernetes config. Inside you will see the name of the project that contains results and reports directories. In the "results" directory check if you have the results allure files that you generated (send it by POST method) and check in the "reports" directory the "latest" directory where you will find the files report generated. 
Seems to be the results directory doesn't contain the results files expected, that is the reason for the NaN% message.
Share the logs when you start the API container, if you see any error about permissions that is the reason you can't see the results directory generated.

Check the previously and share the container logs if you need help.
