### ISSUE TITLE
directory access issues - what should the mounts look like?

### ISSUE THREAD

**Issue by ardz** [fescobar/allure-docker-service#166]
hello, have followed the instructions and also read through the existing issues for this but can't get it working - I'm obviously missing something.

the docker compose file looks like this:

`version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    user: 1002:1002
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/app/projects
      - ${PWD}/allure-results:/app/allure-results

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"`

the error is

`Attaching to rich_allure_1
allure_1     | Not checking results automatically
allure_1     | ALLURE_VERSION: 2.13.8
allure_1     | Generating default report
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports': No such file or directory
allure_1     | Creating results directory for PROJECT_ID: default
allure_1     | mkdir: cannot create directory ‘/app/allure-docker-api/static/projects/default’: Permission denied
allure_1     | Creating executor.json for PROJECT_ID: default
allure_1     | Generating report for PROJECT_ID: default
allure_1     | /app/generateAllureReport.sh: line 59: /app/allure-docker-api/static/projects/default/results/executor.json: No such file or directory
allure_1     | [INFO] /app/allure-docker-api/app.py:290 Setting SECURITY_ENABLED=0 by default
allure_1     | /app/allure-docker-api/static/projects/default/results does not exist
allure_1     | Could not generate report
allure_1     | java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default
allure_1     |  at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
allure_1     |  at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)
allure_1     |  at java.base/java.nio.file.Files.createDirectories(Unknown Source)
allure_1     |  at io.qameta.allure.CommonJsonAggregator.aggregate(CommonJsonAggregator.java:51)
allure_1     |  at io.qameta.allure.CompositeAggregator.aggregate(CompositeAggregator.java:43)
allure_1     |  at io.qameta.allure.ReportGenerator.aggregate(ReportGenerator.java:53)
allure_1     |  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:70)
allure_1     |  at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
allure_1     |  at io.qameta.allure.Commands.generate(Commands.java:104)
allure_1     |  at io.qameta.allure.CommandLine.run(CommandLine.java:152)
allure_1     |  at io.qameta.allure.CommandLine$$Lambda$11/0000000098440100.get(Unknown Source)
allure_1     |  at java.base/java.util.Optional.orElseGet(Unknown Source)
allure_1     |  at io.qameta.allure.CommandLine.main(CommandLine.java:88)
allure_1     | ls: cannot access '/app/allure-docker-api/static/projects/default/reports/*': No such file or directory
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Retrying call http://localhost:5050/allure-docker-service/emailable-report/render?project_id=default in 2 seconds
allure_1     | Timeout requesting  after 7 attempts
`

the PWD location for my user has the following in:

allure-results
docker-compose.yml
projects

I'm lost now. 

The documentation doesn't really explain how to mount the required volumes if that's what I'm missing. Assistance would be much appreciated.

**Comment by fescobar** [comment]
Read the doc in detail @ardz 
https://github.com/fescobar/allure-docker-service#known-issues

**Comment by ardz** [comment]
@fescobar when calling docker compose even passing my user into the yml, it's creating the directories with root as the user:

![image](https://user-images.githubusercontent.com/6310248/130321960-1649276b-ccdc-472d-aa51-4043dee1ce83.png)
