### ISSUE TITLE
is there a fix for the "network error" when trying to access the UI?

### ISSUE THREAD

**Issue by ardz** [fescobar/allure-docker-service#167]
I've followed the "fix" instructions but it doesn't work. I'm definitely using the latest docker image of the API.

The API is accessible.

`"Network Error"
Check if you have access to http://localhost:5050/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)

`{"message":"Network Error","name":"Error","fileName":"http://X.X.X.X:5252/static/js/2.fc83d11e.chunk.js","lineNumber":2,"columnNumber":70398,"stack":"e.exports@http://X.X.X.X:5252/static/js/2.fc83d11e.chunk.js:2:70398\ne.exports/</p.onerror@http://X.X.X.X:5252/static/js/2.fc83d11e.chunk.js:2:69367\n","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:5050/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"withCredentials":true}}`

**Comment by ardz** [comment]
the issue was the ui was trying to access the api via localhost

changing to the IP address of the machine running docker or the hostname fixes the issue.

**Comment by fescobar** [comment]
@ardz that is your local configuration. It's not normal that you have blocked the localhost.
