### ISSUE TITLE
History count increasing for all the test cases

### ISSUE THREAD

**Issue by pzkaram** [fescobar/allure-docker-service#174]
Whenever I run generate-report api or click the generate-report button in UI, the history counts increases for all the test cases irrespective of that test case is executed before generating latest report.

I expected that the history count will increase only for the latest executed test cases before generating report. But currently, the history counts increases for all the test cases.

**Comment by fescobar** [comment]
@pzkaram that is the way it works native Allure framework. No possible to change.
