### ISSUE TITLE
Visiting report link when not logged in does not redirect to login

### ISSUE THREAD

**Issue by sylvain-viole** [fescobar/allure-docker-service#179]
When trying to access a report thru its URL while not logged in, I am getting an authentification error :
![image](https://user-images.githubusercontent.com/71819292/145980307-98e6be2b-ed16-4c4f-b465-515317bd06ad.png)

--> expected behavior : being redirected to LOGIN page, then to request URL after successful login

**Comment by fescobar** [comment]
@sylvain-viole if you have enabled the security then everybody needs to be logged to access.  At least, you want to have some endpoints public. Check this https://github.com/fescobar/allure-docker-service#make-viewer-endpoints-public

**Comment by sylvain-viole** [comment]
I did not notice the MAKE_VIEWER_ENDPOINTS_PUBLIC,
I'll give it a try this afternoon.

Thanks !

**Comment by fescobar** [comment]
@sylvain-viole let me know if you have any other questions. Thanks!
