### ISSUE TITLE
FEATURE : login redirect on not logged visit

### ISSUE THREAD

**Issue by sylvain-viole** [fescobar/allure-docker-service#180]
- We use ALLURE in our slack integration and therefore have direct link to allure reports.
- Our allure docker service is log in enabled
- We do not want the reports to be public

Would it be possible to redirect visitor to the log in page after clicking on a report link while not logged in ?

Thanks !

**Comment by fescobar** [comment]
Hi @sylvain-viole
For the API container enable the security https://github.com/fescobar/allure-docker-service#enable-security
And use the UI container https://github.com/fescobar/allure-docker-service-ui. In there we have the login form implemented.
![image](https://user-images.githubusercontent.com/1236418/146349094-854d5e0e-7dff-406c-84fa-7a331dd3ef6a.png)
![image](https://user-images.githubusercontent.com/1236418/146349119-1a5f0485-1b16-46c7-8250-9f3ec4f3366a.png)
Thank you
