### ISSUE TITLE
getting error : "value of flag --commit-sha (\"\") is invalid: hex data must have length 40 but got 0"

### ISSUE THREAD

**Issue by shuklaa1** [fescobar/allure-docker-service#181]
I am able to run the tests in docker and get the allure report when I do a commit and git push. 
Bt when I merge the PR in main, the checks run again and I get below error in allure report:

`Run docker run -v "${GITHUB_WORKSPACE}"/tests/blackbox/allure-tests-results:/allure-results \
Unable to find image 'anzx-docker.artifactory.gcp.anz/cosmos/allure:dd7d62c' locally
dd7d62c: Pulling from cosmos/allure
64a5500c571d: Pulling fs layer
424247c60328: Pulling fs layer
64a5500c571d: Verifying Checksum
64a5500c571d: Download complete
64a5500c571d: Pull complete
424247c60328: Verifying Checksum
424247c60328: Download complete
424247c60328: Pull complete
Digest: sha256:1de381c55d120005555449d8df9ac9982f803c72e84765b797614505d4509242
Status: Downloaded newer image for anzx-docker.artifactory.gcp.anz/cosmos/allure:dd7d62c
time="2021-12-03T01:20:23Z" level=fatal msg="value of flag --commit-sha (\"\") is invalid: hex data must have length 40 but got 0"
Error: Process completed with exit code 1.`

Please guide

**Comment by fescobar** [comment]
@shuklaa1 can you clarify what commands are you running and where?
That log is not related to `allure-docker-service` it's related to your environment. 
Please, give me more details
