### ISSUE TITLE
send_results.sh: line 56: /mingw64/bin/curl: Argument list too long

### ISSUE THREAD

**Issue by lozzzt** [fescobar/allure-docker-service#183]
If array with test results is too large (more than 100 items), then i get an error 
`send_results.sh: line 56: /mingw64/bin/curl: Argument list too long`
in line:

`RESPONSE=$(curl -X GET "$ALLURE_SERVER/allure-docker-service/generate-report?project_id=$PROJECT_ID&execution_name=$EXECUTION_NAME&execution_from=$EXECUTION_FROM&execution_type=$EXECUTION_TYPE" -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" -ik -b cookiesFile $FILES)`

**Comment by fescobar** [comment]
@lozzzt that is a limitation from curl, split the results

**Comment by lozzzt** [comment]
Splitting by 100 files in report helps:

```
i=0
declare -a FILES
for FILE in $FILES_TO_SEND; do
  i=$((i+1))
  n=$((i / 100))
  FILES[n]+="-F files[]=@$FILE "
done
```
...
```
for ((i=0;i<${#FILES[*]};i++)); do
  echo "------------------SEND-RESULTS------------------"
  curl -X POST "$ALLURE_SERVER/allure-docker-service/send-results?project_id=$PROJECT_ID" -H 'Content-Type: multipart/form-data' -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" -ik -b cookiesFile ${FILES[i]}
  echo "------------------GENERATE-REPORT------------------"
  RESPONSE=$(curl -X GET "$ALLURE_SERVER/allure-docker-service/generate-report?project_id=$PROJECT_ID&execution_name=$EXECUTION_NAME&execution_from=$EXECUTION_FROM&execution_type=$EXECUTION_TYPE" -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" -ik -b cookiesFile ${FILES[i]})
done
```

**Comment by prafair** [comment]
@fescobar for me [this](https://github.com/fescobar/allure-docker-service/issues/183#issuecomment-1031410556) solution doesn't work. In History we have duplicated tests and in general Trend:

<img width="752" alt="Снимок экрана 2023-02-10 в 10 20 10" src="https://user-images.githubusercontent.com/15040493/218027824-99c70e44-b72c-4f22-beeb-875d180525a6.png">
<img width="287" alt="Снимок экрана 2023-02-10 в 10 19 22" src="https://user-images.githubusercontent.com/15040493/218027837-f2bfd91b-0296-4b1d-9646-a1a576cb3357.png">

**Comment by fescobar** [comment]
@prafair 
Before generating new results, you clean the results. Also this:
https://github.com/fescobar/allure-docker-service#multiple-projects---remote-reports

![image](https://user-images.githubusercontent.com/1236418/218099495-b996678d-49a2-47ee-8e23-10619a71a554.png)

**Comment by prafair** [comment]
@fescobar 

Big thank you!

`CHECK_RESULTS_EVERY_SECONDS` was `NONE` in my case.

I just removed the report generation from the loop.
Also I removed `${FILES[i]}` from the generation request:

```
for ((i=0;i<${#FILES[*]};i++)); do
  echo "------------------SEND-RESULTS------------------"
  curl -X POST "$ALLURE_SERVER/allure-docker-service/send-results?project_id=$PROJECT_ID" -H 'Content-Type: multipart/form-data' -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" -ik -b cookiesFile ${FILES[i]}
done

echo "------------------GENERATE-REPORT------------------"
RESPONSE=$(curl -X GET "$ALLURE_SERVER/allure-docker-service/generate-report?project_id=$PROJECT_ID&execution_name=$EXECUTION_NAME&execution_from=$EXECUTION_FROM&execution_type=$EXECUTION_TYPE" -H "X-CSRF-TOKEN: $CRSF_ACCESS_TOKEN_VALUE" -ik -b cookiesFile)
```
