### ISSUE TITLE
How change name default project with use docker-compose.yml 

### ISSUE THREAD

**Issue by Mikhailnt87** [fescobar/allure-docker-service#184]
Tell me please, how change name default project with use docker-compose.yml? 
I want change name default project, but change name project in folder "projects" and docker commit frankescobar/allure-docker-service on new image - fails

"Network Error"
Check if you have access to http://localhost:5050/allure-docker-service
Or pull the latest "frankescobar/allure-docker-service" API image (remove your current latest version)
{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at e.exports (http://localhost:5252/static/js/2.fc83d11e.chunk.js:2:70398)\n at XMLHttpRequest.p.onerror (http://localhost:5252/static/js/2.fc83d11e.chunk.js:2:69367)","config":{"url":"/config","method":"get","headers":{"Accept":"application/json, text/plain, */*"},"baseURL":"http://localhost:5050/allure-docker-service","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"withCredentials":true}}

**Comment by fescobar** [comment]
@Mikhailnt87 you can't change the default name project. That is created by default. You can create new ones.

**Comment by Mikhailnt87** [comment]
thanks a lot for the info
