### ISSUE TITLE
Problem is to generate an allure report when running tests and services in a container

### ISSUE THREAD

**Issue by Mikhailnt87** [fescobar/allure-docker-service#185]
Please tell me how to fix the error for my configuration.
- launching docker-compose.yml test + services
- tests are built  and launching from Dockerfile
- error: /app/generateAllureReport.sh: line 59: /app/allure-docker-api/static/projects/default/results/executor.json: Permission denied

docker-compose yml:
version: '3'
services:
  test_runner:
    build:
      context: C:\QA_AUTOMATION\WebPlaywright
      dockerfile: C:\QA_AUTOMATION\WebPlaywright\Dockerfile
    image: web_tests_playwright
    container_name: web_tests_run_playwright
    network_mode: "host"
  allure:
      image: "frankescobar/allure-docker-service"
      user: ${MY_USER}
      environment:
        EMAILABLE_REPORT_TITLE: "AutoSmoke_MFTV_Web_and_Mobile_Web"
        CHECK_RESULTS_EVERY_SECONDS: 1
        KEEP_HISTORY: 1
      ports:
        - "5050:5050"
      volumes:
        - /gradle/build/allure-results:/app/allure-results
        - /gradle/build/reports/allure-report:/app/default-reports
  allure-ui:
        image: "frankescobar/allure-docker-service-ui"
        environment:
          PROJECT_ID: "autosmoke-mftv-web-and-mobile-web"
          EMAILABLE_REPORT_TITLE: "AutoSmoke_MFTV_Web_and_Mobile_Web"
          ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
          ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
        ports:
          - "5252:5252"
        
Dockerfile:
FROM mcr.microsoft.com/playwright/java:v1.18.0-focal
## Install node14
RUN apt update && apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt install -y nodejs

## Upgrade to NPM7
RUN npm install -g npm@8

## Install stable chrome 
RUN npx playwright install chrome

RUN apt-get update && apt-get install -y unzip
WORKDIR /gradle
RUN curl -L https://services.gradle.org/distributions/gradle-6.0.1-bin.zip -o gradle-6.0.1-bin.zip
RUN unzip gradle-6.0.1-bin.zip
ENV GRADLE_HOME=/gradle/gradle-6.0.1
ENV PATH=$PATH:$GRADLE_HOME/bin
COPY . .
CMD gradle clean test allureReport allureServe

**Comment by fescobar** [comment]
@Mikhailnt87 I recommend you don't use this image as a base.
Just create your own image related to your framework and share the same volume (directory) to share the results files.

The same, any issue with permissions check here:
https://github.com/fescobar/allure-docker-service#known-issues
https://github.com/fescobar/allure-docker-service/issues/108
