### ISSUE TITLE
Get overall testcases count in latest report

### ISSUE THREAD

**Issue by niranjanitt** [fescobar/allure-docker-service#186]
I want to get total number of testcases (unique testcases) ran throughout my the execution as part of regression testing.
I am able to get the count when I don't call clean results api but it has an issue on the history tab for non executed testcases well
when i call clean results api before generating report I am always getting latest execution testcase number not the overall 
do we have an option to see the overall testcase executed in allure report.

**Comment by fescobar** [comment]
@niranjanitt that is a limitation from Allure native.
