### ISSUE TITLE
how to change logo url  point to latest

### ISSUE THREAD

**Issue by niranjanitt** [fescobar/allure-docker-service#187]
Is it possible to update environmental variable to update url link of the allure logo in the report, currently it is pointing to the history which i have opened I need to point that to always latest of the project.

![image](https://user-images.githubusercontent.com/98308629/155308602-88c5c4bd-3bd1-4d7a-8ac5-e73ff424e6d3.png)

**Comment by fescobar** [comment]
Sorry @niranjanitt. It's a limitation from the native Allure.

**Comment by EsakkiappanA** [comment]
@fescobar do we have any other work around to navigate back to Latest report(URL) other than manually changing URL to latest.

**Comment by fescobar** [comment]
@EsakkiappanA why don't use https://github.com/fescobar/allure-docker-service-ui

**Comment by EsakkiappanA** [comment]
@fescobar We are developing our own dashboard for org level to show all project related data and test execution. As of now the project teams using the allure docker and they feel like changing the URL to latest is always a bad idea, just trying to figure out do we have any option

**Comment by fescobar** [comment]
@EsakkiappanA As I said before, I can't control all the things in the allure native report. Allure Docker Service is a wrapper.
