### ISSUE TITLE
Request for Accordion(collapsible section)  in email report 

### ISSUE THREAD

**Issue by rupeshkumar-somala-by** [fescobar/allure-docker-service#188]
This could compress the view and able to observe maximum content at a stretch. 

Reference: 
https://stackoverflow.com/questions/50963755/expand-collapse-content-with-css-in-html-mail
https://email.uplers.com/accordion-in-email/

**Comment by rupeshkumar-somala-by** [comment]
Attaching a sample screenshot for view
![image](https://user-images.githubusercontent.com/85099773/156802855-5ff81d2f-4d2d-41d0-b8d9-fa3e8c0ff288.png)

**Comment by fescobar** [comment]
You can fork the project and implement your improvements.
