### ISSUE TITLE
Send Screenshots through API

### ISSUE THREAD

**Issue by manuschillerdev** [fescobar/allure-docker-service#189]
Thanks for you great allure setup!
I am wondering if it would be possible to send screenshots as report attachments as well. 
Could that be done?

I looked into https://github.com/fescobar/allure-docker-service#send-results-through-api, but I think this only describes sending allure results/reports, right?

**Comment by fescobar** [comment]
@manuschillerdev try with the scripts first before opening an issue. You can send screenshots and videos too.
