### ISSUE TITLE
Created new api client

### ISSUE THREAD

**Issue by MMark4** [fescobar/allure-docker-service#191]
Hello! I created a new client to connect to the api in form of a npm package, tried to add a pull request with docs on readme but was not possible as I dont have that permissions, this was what i wanted to add.

* 3rd party NPM package that connects with the service to send results, not mantained by @fescobar.
  * [Package](https://www.npmjs.com/package/allure-service-client)
  * [Github](https://github.com/Saetabis1/allure-service-client)

**Comment by fescobar** [comment]
Hi @Saetabis1 
If you want to create a PR in this repository, you need to fork the project under your user, after that you can push your changes in your forked repo and then when is finished you can create a Pull Request here against your project/branch forked.
You have some simple tutorials, but here it's described how to do that by github.
- https://docs.github.com/en/github-ae@latest/get-started/quickstart/fork-a-repo
- https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Please, when you create the PR do it against `beta` branch not use my `main` branch.
If you want to add info about your client, please add that part above `SUPPORT` section with the title `COMPLEMENTARY EXTERNAL TOOLS`. Something like this:

```sh
## COMPLEMENTARY EXTERNAL TOOLS
### API Clients
#### allure-service-client (NPM)
```

Thank you for your contribution.
