### ISSUE TITLE
Generated reports do not include custom Allure plugin 

### ISSUE THREAD

**Issue by Merckan** [fescobar/allure-docker-service#196]
Hi! I mount volume with my custom plugin's data.
${PWD}/plugins/warnings-plugin:/allure/plugins/warnings-plugin
But plugin is absent in my generated reports.
I didn't found config/allure.yml inside allure-docker-service container. This file is using for register plugins, including custom ones.

**Comment by fescobar** [comment]
@Merckan can you access the container using bash (`docker exec -it ${CONTAINER_ID} bash`) and run the command `ls` to see what is inside of the directory `/allure/plugins` and `/allure/plugins/warnings-plugin`, maybe is not mounted properly.
