### ISSUE TITLE
[feature]: Emailable report, want to show filtered cases results below the summary when we click the Passed/Failed etc...

### ISSUE THREAD

**Issue by kisscelia** [fescobar/allure-docker-service#197]
![image](https://user-images.githubusercontent.com/13063673/173973043-aba1eca2-2f00-4c1c-8d7c-dd04d36757e3.png)

**Comment by fescobar** [comment]
You can build your own custom emailable report.
https://github.com/fescobar/allure-docker-service#develop-a-new-template
