### ISSUE TITLE
Latest results not updated on allure

### ISSUE THREAD

**Issue by JackyShao01** [fescobar/allure-docker-service#199]
Hi,

We are consuming allure-docker-service running on Fargate - We can successfully upload results and see generated report from the link allure-docker-servic-UI being provided. however when the results are getting increased , we are facing the issue which the latest result got delayed to be uploaded and get 413 http status code. 

We assume that payload in request to one of instance in Fargate is too big so that 413 http status error occurs.
The payload includes all links such as .txt and .json files. How should we fix this problem? 

We are not sure the real reason. We can provide the full log if required. 

Thank you in advance.

**Comment by fescobar** [comment]
Split the results.

**Comment by Saurabhrck** [comment]
@fescobar Could you please elaborate? If we split the results that would create multiple report in allure. Is there any way to upload large result sets?

**Comment by fescobar** [comment]
@Saurabhrck If you have 1000 results files to upload, then split those results into small parts and send them individually. I mean send 100, after 100 more until reaching the 1000 files.

**Comment by Saurabhrck** [comment]
@fescobar Owo. Did not know we could do that. Just made some changes to python script and it worked like a charm. 1.1 GB uploaded and generated report properly.

Thanks for the help.
