### ISSUE TITLE
Executors link error

### ISSUE THREAD

**Issue by francesco-midokura** [fescobar/allure-docker-service#202]
The executors section in allure docker UI (v2.17.2) has an issue, the link is not working as it is made like this:
`<a class="link" href="=https://github.com/project/actions/runs/1234567">
                        project_id #1
                        <span class="fa fa-external-link"></span>
                    </a>`

Rather then showing the github action run page by clicking, it shows the response of the GET project:
`{"data":{"project":{"id":"project_id","reports":["URI/allure-docker-service/projects/project_id/reports/latest/index.html","https://URI/allure-docker-service/projects/project_id/reports/1/index.html"],"reports_id":["latest","1"]}},"meta_data":{"message":"Project successfully obtained"}}` 

The issue could be resolve by adding:
`target="_blank"` in the html element, and removing '=' in the href value.

**Comment by fescobar** [comment]
I don't have control over Allure Report, I'm opening that report in an iframe.
