### ISSUE TITLE
When using K8's SECURITY_ENABLED env var does not get passed correctly

### ISSUE THREAD

**Issue by MMark4** [fescobar/allure-docker-service#205]
When I set SECURITY_ENABLED as a string in my helm chart yaml It does not get recognized and defaults in 0, I can not use integers as this known issue in kubernetes  https://github.com/kubernetes/kubernetes/issues/82296 

Helm chart 

> spec:
>     helm-values:
>       encryptedData:
>         SECURITY_PASS: >- Here is set the value
>         SECURITY_USER: >- Here is set the value
>         SECURITY_VIEWER_PASS: >- Here is set the value
>         SECURITY_VIEWER_USER: >- Here is set the value
>       env:
>         - name: CHECK_RESULTS_EVERY_SECONDS
>           value: NONE
>         - name: KEEP_HISTORY
>           value: '1'
>         - name: KEEP_HISTORY_LATEST
>           value: '201'
>         - name: SECURITY_ENABLED
>           value: '1'
>       image:
>         repository: frankescobar/allure-docker-service
>         tag: 2.19.0

Logs

> root@897bc2d08750:~/management# k logs testing-allure-api-sdet-576fffd565-l4d68 -n allure
> Not checking results automatically
> ALLURE_VERSION: 2.19.0
> Generating default report
> Creating executor.json for PROJECT_ID: default
> Generating report for PROJECT_ID: default
> [INFO] /app/allure-docker-api/app.py:294 Setting SECURITY_ENABLED=0 by default
> Report successfully generated to /app/allure-docker-api/static/projects/default/reports/latest
> Status: 200
> 2022-10-05 06:45:36.758:INFO::main: Logging initialized @1136ms to org.eclipse.jetty.util.log.StdErrLog

Can we (and as we I compromise to make the change) modify the usage of integer 1 in new version but the usage of string 'true' or 'false'?

Or maybe Its a known issue and I did not read correctly.

Nonetheless thanks for the work on this one

**Comment by fescobar** [comment]
@MMark4 you need to pass the integer as a string `'1'`.
Check the example https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-kubernetes-example/allure-config-map.yml#L11
