### ISSUE TITLE
Allure server auto generate reports after call api /send-result

### ISSUE THREAD

**Issue by binhdao112** [fescobar/allure-docker-service#208]
Allure reports auto generate while using api /send-result to send json file to server and don't respone message report_url. i must call api /generate-report to get it so it's duplicate my report. how to solved ?

**Comment by fescobar** [comment]
If you use automatic reports a daemom is created and it will be listening any change in the results directory it will generate a new report each time find a new file. The same will happen for every project. For that reason, it's convenient disable the automatic reports using the value NONE in CHECK_RESULTS_EVERY_SECONDS.
