### ISSUE TITLE
Allure UI does not work with remote servers

### ISSUE THREAD

**Issue by alonbnhubsecurity** [fescobar/allure-docker-service#209]
Hello,
I have used allure server and allure ui docker on my remote server and when I am trying to access it locally from my computer allure is unable to show me the results and reports (I ran the containers locally with the same data and it worked).
What did I do:
```
docker run -d -p 5252:5252 -e ALLURE_DOCKER_PUBLIC_API_URL=http://<REMOTE_SERVER_IP>:5050 --name allure-docker-service-ui frankescobar/allure-docker-service-ui:latest
```
Notice that when I run `http://<REMOTE_SERVER_IP>:5050/generate-report?project_id=test` it does seems to work for me.

I read the decantation you added but I can't seems to find any mention of remote usage.
Am I missing something or is it just not compatible for remote usage? and if so what is the point of the docker if I can just run server on my results locally?

The reason I am writing it here is because it doesn't seems like there is any response in the allure UI repo.

**Comment by alonbnhubsecurity** [comment]
I managed to make it work with the [k8s examples](https://github.com/alonbnhubsecurity/allure-docker-service-examples/tree/master/allure-docker-kubernetes-example#creating-a-node-port-service)

**Comment by fescobar** [comment]
> I managed to make it work with the [k8s examples](https://github.com/alonbnhubsecurity/allure-docker-service-examples/tree/master/allure-docker-kubernetes-example#creating-a-node-port-service)

The repo that you shared is not public.

**Comment by alonbnhubsecurity** [comment]
It seems that it was deleted or moved.

**Comment by fescobar** [comment]
@alonbnhubsecurity maybe this one?
https://github.com/fescobar/allure-docker-service-examples/tree/master/allure-docker-kubernetes-example#creating-a-node-port-service
