### ISSUE TITLE
Historical trend for more than 20 runs and surfacing browser-os combination in the report.

### ISSUE THREAD

**Issue by swatinigam** [fescobar/allure-docker-service#214]
Hi @fescobar, If I set KEEP_HISTORY:1  and I set KEEP_HISTORY_LATEST: 60, is it right that the graphs related to trends would show trends going back to last 60 test runs? 

Also, is there a way to populate the environment variables widget with the browser and os combination? We are using browserstack to run our Cypress tests and we expect to run our tests on a few different browsers and OSes. It would be great to see that information in the report. If you have any advice about it, please do share. 

Thank you for your work on this service.

**Comment by fescobar** [comment]
Hi @swatinigam 
Allure native framework only shows 20 last results as max. But you can use the API to get all history stores or you can use Allure Docker Service UI
Everything is specified here: https://github.com/fescobar/allure-docker-service#keep-history-and-trends

**Comment by fescobar** [comment]
@swatinigam Related different kind of browsers, you can pass allure parameters from your code. How? depends on your programming language. This is an example: https://docs.qameta.io/allure/#_parametrization
