### ISSUE TITLE
Email report not rendering correctly in GMail

### ISSUE THREAD

**Issue by nicon89** [fescobar/allure-docker-service#220]
Generated rendered emails are not rendering correctly in GMail:
![image](https://user-images.githubusercontent.com/9640905/233387822-fb4adfd1-f68b-441b-9dc1-c4d2d33284c4.png)
Expected result:
![image](https://user-images.githubusercontent.com/9640905/233388977-d29a1171-0a59-453a-a23e-92b5db814729.png)

Steps to reproduce:
```
curl -XGET https://allure-api/allure-docker-service/emailable-report/render/?project_id=default -b cookiesFile  > email.html
ssmtp email@address.com < email.html
```

Am I doing something wrong, or is it expected?

**Comment by fescobar** [comment]
@nicon89 Just you need to open the HTML in any browser. Once it's rendered just select all and copy the content.
In the email just you need to paste the content previously copied.
![image](https://github.com/fescobar/allure-docker-service/assets/1236418/5acb4730-2198-4f1e-9ee9-9bdfe8bc978c)

**Comment by nicon89** [comment]
What if I want to to use an automated script to send it?

**Comment by fescobar** [comment]
@nicon89 depends on the tech that you implement you will find libraries to send HTML in emails.
