### ISSUE TITLE
enable 3rd SSO like Github SSO

### ISSUE THREAD

**Issue by victor-wang-anz** [fescobar/allure-docker-service#225]
hey @fescobar  I am just wondering if it's possible to introduce SSO feature to enhance the security. 
For example I am currently researching enable Github SSO for this service, so user Authed with Github SSO from the allure docker service ui can take different actions

**Comment by fescobar** [comment]
Hi @victor-wang-anz 
The current features are not enough to improve the security. It's a simple project.
