### ISSUE TITLE
Cannot create directory ‘/app/allure-docker-api/static/projects/default’: Permission denied

### ISSUE THREAD

**Issue by YufeeXing** [fescobar/allure-docker-service#226]
When I follow this(https://github.com/fescobar/allure-docker-service#multiple-project---docker-compose) to run docker-compose command in my VM.
The logs of the container show somer error:
![image](https://github.com/fescobar/allure-docker-service/assets/42690790/942be356-f738-426b-bda9-4ab706ddce6d)
The /allure-docker-service/#/Project/get_projects can be visited but return an empty project list.
![image](https://github.com/fescobar/allure-docker-service/assets/42690790/77762f26-0365-4010-9481-ea40214b1983)
The /allure-docker-service/#/Project/post_projects return an error code 400
![image](https://github.com/fescobar/allure-docker-service/assets/42690790/dab79027-b3fd-4787-b987-ab94daf2123a)

**Comment by YufeeXing** [comment]
![image](https://github.com/fescobar/allure-docker-service/assets/42690790/27ef1149-f955-424c-a0d7-de7c98759b39)

**Comment by wenmhan** [comment]
hi，how did you solve this problem?
