### ISSUE TITLE
Allure properties

### ISSUE THREAD

**Issue by erikpb** [fescobar/allure-docker-service#23]
Is there a way to specify Allure properties, e.g. allure.tests.management.pattern as seen in https://github.com/allure-framework/allure1/wiki/Test-Case-ID?

**Comment by fescobar** [comment]
@erikpb that doc is for Allure1, allure-docker-service is using Allure2.
Did you read how to implement that on Allure2?

**Comment by erikpb** [comment]
Sorry I mean the parameters at https://docs.qameta.io/allure/#_jenkins. Didn’t see anything in your doc about it unless I’m missing something?

**Comment by fescobar** [comment]
This is a docker container to use in kubernetes, docker-compose or locally with docker. If you want to use Allure on Jenkins you need to install Allure Plugin on the master machine on jenkins server as it said in the doc that you shared me
   https://wiki.jenkins.io/plugins/servlet/mobile?contentId=72419280#content/view/72419280

**Comment by erikpb** [comment]
Sorry for not being clear. My question is basically how can I set parameters such as allure.tests.management.pattern when running a container based on your image. I know how to do it when running Allure in Jenkins and was hoping to be able to do it when running your container too.

**Comment by fescobar** [comment]
@erikpb Give me a few days to try that. I will add the documentation or I'll do some changes if it's not supported. Thank you.

**Comment by fescobar** [comment]
@erikpb what framework are you using?

**Comment by erikpb** [comment]
I'm using Behat with the Allure Behat https://github.com/allure-framework/allure-behat plugin to generate the XML files.

**Comment by fescobar** [comment]
@erikpb if you have a mini project with your configuration would be better. Thanks

**Comment by erikpb** [comment]
Below is an example of a file that is generated. 
The content of the issue and testid tags appear in the Link section when viewing the scenario in Allure, however it appears like http://localhost:4040/AP014 and I want to be able to specify something like https://my-issue-manager.com/AP014.

`
<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1558703737592" stop="1558703744538" version="1.4.0">
  <name>trello</name>
  <test-cases>
    <test-case start="1558703737684" stop="1558703744514" status="pending">
      <name>/var/www/app/tests/ocp/trello/features/Accounts/CU040.feature:10</name>
      <title>Not implemented 3</title>
      <description type="text">
  As a back-office user,
  I should be able to suspend and un-suspend an account and record the reason for suspension
    </description>
      <steps>
        <step start="1558703742763" stop="1558703744375" status="canceled">
          <name>not implemented</name>
          <title>Given not implemented</title>
        </step>
      </steps>
      <labels>
        <label name="epic" value="Trello"/>
        <label name="feature" value="Accounts"/>
        <label name="story" value="Suspended accounts"/>
        <label name="issue" value="CU040"/>
        <label name="testId" value="W3Qd1xzV"/>
      </labels>
    </test-case>
  </test-cases>
</alr:test-suite>
`

**Comment by fescobar** [comment]
@erikpb I mean, if you can create a project using Behat with some empty tests using your configuration.

**Comment by erikpb** [comment]
Unfortunately it's a corporate project with lots of dependencies so that won't work. However if I run that same file via the Jenkins Allure set up it generates the links correctly. There must be some sort of command line configuration but having looked through the Allure documentation I haven't found any.

**Comment by fescobar** [comment]
Hi @erikpb I've done this simple example. Execute in the root `composer install` and after that `vendor/bin/behat`. Can you set up that example to generate `allure-results` folder in the project with the results files and upload it here?
[frank-behat.zip](https://github.com/fescobar/allure-docker-service/files/3272016/frank-behat.zip)
I need this to check if the fix it's working.
Thank you.

**Comment by fescobar** [comment]
@erikpb Also, could you add all files from your `allure-results` directory? I need to see if it's rendered properly in the Allure report, only I have the xml `testsuite.xml`, if you want you could update some critical data.

**Comment by fescobar** [comment]
@erikpb I have the solution. It's documented here: https://github.com/fescobar/allure-docker-service#using-allure-options.
Just you need to add `ALLURE_OPTS` environment variable to your container with the values `-Dallure.tests.management.pattern=https://example.org/tms/%s -Dallure.issues.tracker.pattern=https://example.org/issue/%s`

`allure-behat` is using. allure1, it should use allure2. For that reason, you need this configuration. I see there is no other framework for `behat`.

Try and let me know if it worked for you.

**Comment by erikpb** [comment]
Fabulous! Will test it out and let you know if any further issues.

**Comment by fescobar** [comment]
@erikpb any update?
