### ISSUE TITLE
Use S3 as volume for reports

### ISSUE THREAD

**Issue by ramsar7002** [fescobar/allure-docker-service#231]
Hi,
We've set up a GitHub action that executes Playwright end-to-end tests, creates a report, and then uploads it to S3. Now, we're interested in integrating the Allure service as a test results reporter and trend analyzer. This gives developers access to their branch runs.
We are wondering how we can use S3 as volume for these different reports?
Thanks.
![Screenshot 2023-09-13 at 8 01 11](https://github.com/fescobar/allure-docker-service/assets/39989110/21b8b806-5ced-4981-8296-37f494cbcc31)

**Comment by fescobar** [comment]
Hi @ramsar7002 
When you deploy allure-docker-service in Kubernetes you can choose any storage like S3 to keep the directory where you save the data.
From CI, you can send the results using the API and generate the reports aiming to the allure docker server deployed.
