### ISSUE TITLE
The access token has expired - redirect to login page?

### ISSUE THREAD

**Issue by nicon89** [fescobar/allure-docker-service#234]
When I click on the report link, generated from:
```
print('ALLURE REPORT URL:')
print(json_response_body['data']['report_url'])
```
I'm getting "The access token has expired" error. Solution is to open a new window, login and refresh report page.
Is there a way to redirect user to the login page instead and after login get back to the requested URL?

**Comment by fescobar** [comment]
@nicon89 that is implemented in the UI https://github.com/fescobar/allure-docker-service-ui
There is no way to implement it from the API. Make sure first you are logged from your script to have a valid token.
