### ISSUE TITLE
Testcase history tab showing same date time for different runs

### ISSUE THREAD

**Issue by SohanTirpude** [fescobar/allure-docker-service#244]
Hello all,

I am seeing same date time for different test case runs. Can anyone please help me out on how to fix this?
<img width="1792" alt="Screenshot 2024-03-05 at 5 25 49 PM" src="https://github.com/fescobar/allure-docker-service/assets/13250447/58f7f9af-6eb1-47da-a0c1-d912086cb8a8">

I am running this job in every 5 minute interval from Jenkins and some times I am seeing this abnormalities. BTW this is the demo test file I am using: https://github.com/fescobar/allure-docker-service-examples/blob/master/allure-docker-python-pytest-example/tests/demo_test.py

Allure version: 2.21.0
Test framework: pytest@8.0.1
Allure adaptor: allure-pytest@2.13.2

**Comment by SohanTirpude** [comment]
Hello @fescobar, we have set the value to `1` to env variable `CHECK_RESULTS_EVERY_SECONDS`.

**Comment by fescobar** [comment]
@SohanTirpude that is the reason. Use CHECK_RESULTS_EVERY_SECONDS=NONE and generate the results using the API.
