### ISSUE TITLE
Infinite loop + 100% CPU if CHECK_RESULTS_EVERY_SECONDS: NONE

### ISSUE THREAD

**Issue by anrock1985** [fescobar/allure-docker-service#30]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
26147 root      20   0   19720   3208   2948 R 100,0  0,0   0:09.91 checkAllureResu

CHECK_RESULTS_EVERY_SECONDS: 3600 works fine

if [ "$CHECK_RESULTS_EVERY_SECONDS" == "NONE" ] || [ "$CHECK_RESULTS_EVERY_SECONDS" == "none" ]; then
	echo "Not checking results automatically"
	**while true ; do continue ; done**
fi

**Comment by fescobar** [comment]
@anrock1985
I did the next change:
```
	while true ; do
		sleep 3600
	done
``` 
Try with new `beta` version (remove the previous beta version in case you used it before) and let me know if the problem was fixed.

**Comment by anrock1985** [comment]
fixed, thanks

**Comment by fescobar** [comment]
@anrock1985 I've released the fix from version `2.12.1`
