### ISSUE TITLE
Upload results on server

### ISSUE THREAD

**Issue by lacell75** [fescobar/allure-docker-service#32]
My tests are executed on Gitlab CI with node image and I wish use this docker image like server to generate report and to keep history execution. 
But how can I upload my results on this server from my job on Gitlab? I didn't see API for that, maybe another way to do that. Can you help me?
thanks

**Comment by fescobar** [comment]
@lacell75 that it will be a new feature (good feature). How do think is the best way to pass those files (results) through API? will you encode your files? Should the container receive an array of files?

http://localhost:5555/upload-allure-results (POST)
```
{
  [ "xxxx", "xxxx"]
}
```

**Comment by lacell75** [comment]
I think the best way to upload file on a server, it is to use a ftp server instead of develop an API. WDYT?

**Comment by fescobar** [comment]
The think is I have already an api. What do you think if you have to encode in base64 and I have to decode it?

**Comment by lacell75** [comment]
I can encode files in base64

**Comment by fescobar** [comment]
Ok, give me a few days. I will have that soon.

**Comment by fescobar** [comment]
@lacell75 In Progress...

**Comment by fescobar** [comment]
Hi @lacell75 
Can you test the new feature with version `beta`??
```
  allure:
    image: "frankescobar/allure-docker-service:beta"
```
The documentation is up to date on branch `api-post-results`: https://github.com/fescobar/allure-docker-service/tree/api-post-results#send-results-through-api
Just in case, I copied the doc here:

**Send results through API**
After running your tests you can execute any script to send the generated results from any server to the Allure container using the Allure API. For that, you can use the endpoint `send-results`.

Here a script in python as example: allure-docker-api-usage/send_results.py
https://github.com/fescobar/allure-docker-service/tree/api-post-results/allure-docker-api-usage
```
cd allure-docker-api-usage
python send_results.py
```
You can access to Swagger doc (http://localhost:5050) to see a simple example:

![image](https://user-images.githubusercontent.com/1236418/63035356-ec559a80-beb2-11e9-8e0b-f071f9cf953e.png)

Please, let me know if you find some issue.

**Comment by fescobar** [comment]
Also, you have another new endpoint `'GET'    /clean-results`

**Comment by fescobar** [comment]
https://github.com/fescobar/allure-docker-service/pull/35

**Comment by fescobar** [comment]
@lacell75 I tested this new feature and it was released on `2.12.1` version. If you have currently that version, remove your local image and download it again.

If you find any issue, please let me know, creating another ticket.
Thank you

**Comment by pghosh-payments** [comment]
@fescobar Thanks for creating the docker image, I am facing below issue if you can suggest: 

100 7556k  100   113  100 7556k    419  27.3M --:--:-- --:--:-- --:--:-- 27.3M
I am getting below error for the report sizes as heavy, is there a way to perform an async operation, or any other way to handle a heavy allure report files:
{"meta_data":{"message":"413 Request Entity Too Large: The data value transmitted exceeds the capacity limit."}}

**Comment by morsa1** [comment]
Same problem here, any news?

`HTTP/1.1 400 BAD REQUEST
Access-Control-Allow-Credentials: true
Content-Length: 113
Content-Type: application/json
Date: Tue, 25 Feb 2025 16:44:35 GMT
Server: waitress

{"meta_data":{"message":"413 Request Entity Too Large: The data value transmitted exceeds the capacity limit."}}`

**Comment by greysky007** [comment]
I also have the same problem. 413 {"meta_data":{"message":"413 Request Entity Too Large: The data value transmitted exceeds the capacity limit."}}`
