### ISSUE TITLE
Allure-maven-docker-plugin

### ISSUE THREAD

**Issue by RaymondMouthaan** [fescobar/allure-docker-service#36]
hi @fescobar,

First of all, very nice to see a Docker project for Allure Reporting 👍 .

I took the opportunity to create an **initially working** [Allure maven docker plugin](https://github.com/RaymondMouthaan/allure-maven-docker-plugin) for it. This plugin publishes the allure results in base64 encoding to a given Docker api. 

For example `http://<your_docker_server_ip>:5050/send-results`. 

This makes it possible to publish the results of test directly to your allure-docker-service right after unit test and/or integration tests.

Greets,
Ray

**Comment by fescobar** [comment]
@RaymondMouthaan good to know this new feature is useful. Thank you so much for the info. It will be useful for all.
