### ISSUE TITLE
[proposal] Multi-Architectures support

### ISSUE THREAD

**Issue by RaymondMouthaan** [fescobar/allure-docker-service#37]
Besides the plugin #36 , i really would like help to build Docker Manifest lists for your project to support multiple architectures (amd64, arm and arm64) for allure-docker-service. This means allure-docker-service also can be deployed on for example a Raspberry PI or PINE64. And is usable in a Docker Swarm with multi-arch nodes.

If you are interested in this and you wouldn't mind to use [TravisCI](https://travis-ci.org) as build server, to automatically build and publish the images to your Docker repo, please let me know :-). 

In that case i'll do a PR with my solution.

Cheers,
Ray

**Comment by fescobar** [comment]
Sounds good. Welcome on board!
I will send you an email to coordinate. Thank you

**Comment by RaymondMouthaan** [comment]
see #38

**Comment by fescobar** [comment]
In Testing...

**Comment by fescobar** [comment]
@RaymondMouthaan Your improvements and the Multi-Architecture support was released on `2.12.1`. Thank you so much for your help. Good job!

**Comment by RaymondMouthaan** [comment]
Glad I could help! I'll move over to use your docker images from now on 👍🏽.
