### ISSUE TITLE
Allure-docker-service Python3

### ISSUE THREAD

**Issue by RaymondMouthaan** [fescobar/allure-docker-service#41]
Hi Frank,

Like we discussed earlier - current images are base on Python 2.7, which has end-of-life at 01/01/2020. 

I took the opportunity to build the images on Python 3 and I think the api works very nicely. Please have a look at my [Allure-Docker-Service](https://cloud.docker.com/repository/docker/raymondmm/allure/tags) images and feel free to test them.

Let me know how they work for you and I'll PR the changes I made.

Greets,
Ray

**Comment by fescobar** [comment]
Ok, let me check your images. Thanks

**Comment by fescobar** [comment]
@RaymondMouthaan If you try generating results with this project https://github.com/fescobar/allure-docker-service/tree/master/allure-docker-java-testng-example and request `http://localhost:5050/emailable-report/render` throws the next error:

```
{
meta_data: {
message: "'str' object has no attribute 'decode'"
}
}
```

**Comment by RaymondMouthaan** [comment]
@fescobar, can you do another try? Should be fixed in the latest beta -> https://cloud.docker.com/repository/docker/raymondmm/allure/tags

**Comment by fescobar** [comment]
@RaymondMouthaan Now it's working fine!. Can you create a PR for `dev` branch?
Thank you so much.

**Comment by fescobar** [comment]
https://github.com/fescobar/allure-docker-service/pull/45

**Comment by fescobar** [comment]
Thank you so much @RaymondMouthaan for your contribution. I've added your changes to master to use Python3. You could see that change applied in version `2.12.1`, remove your images and pull again if you had the same version in your machines.

**Comment by RaymondMouthaan** [comment]
@fescobar, Glad to help some improvements to this project 👍🏽.
