### ISSUE TITLE
add report summary to emailable report template

### ISSUE THREAD

**Issue by akz786** [fescobar/allure-docker-service#47]
Hi can we please add a report summary to the emailable report template (default.html), similar to what is on the dashboard of the allure report.

Ideally you want the following:
1)  Test Case percentage passed overall
2) Total number of Test cases Passed
3) Total number of Test cases Failed
4) Total number of test cases Broken/Skipped (if possible to do this)

Thanks

**Comment by fescobar** [comment]
Hi @akz786 
Thanks for your suggestion. The improvement was released in `2.13.0`, just pull the new version and let me know if you find any issue.

![image](https://user-images.githubusercontent.com/1236418/64528532-9ed91b80-d300-11e9-99fe-1600f7fa4f74.png)

https://github.com/fescobar/allure-docker-service/pull/48
