### ISSUE TITLE
Query: Add authentication to the report

### ISSUE THREAD

**Issue by techhemant** [fescobar/allure-docker-service#56]
Hosting this report in a container would make it available to everyone with the URL as it doesn't have any authentication method. We use Google cloud to host our service. Could you please advice what should be done to add authentication to it?

**Comment by fescobar** [comment]
@techhemant that is something your DevOps team should resolve. You could have this service deployed in a VPN or you could restrict access with HTTP Basic Authentication using load balancers like NGINX or anyother.
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

The security layer is not the responsibility of this container.

**Comment by techhemant** [comment]
@fescobar Thanks for the explanation. I get the idea.

**Comment by fescobar** [comment]
@techhemant you’re welcome.

**Comment by fescobar** [comment]
@techhemant I'm building a security layer, it will e ready soon.
https://github.com/fescobar/allure-docker-service/issues/95
