### ISSUE TITLE
Add endpoint to export report data (zip)

### ISSUE THREAD

**Issue by karolxavierleite** [fescobar/allure-docker-service#60]
I have a specific need for an endpoint to export report data.

I work with many (many) different teams on the same mobile app and I want to aggregate all test results from each team... but I want to create views for each test cycle separated by app version.

What happens in my reality:

1. we create a new app version (eg 1.0)
2. teams starting testing
3. when tests are done, we release the app
4. we create the next app version (eg 2.0)
5. teams starting testing and so on.

In my case, it would be very helpful if I could export each report data after tests are done. With this service, I will save report data on s3 bucket and clean the container for the new test cycle (new version).

What do you think? I can explain in more details if needed.

Thanks.

**Comment by fescobar** [comment]
@karolxavierleite can you try with the new endpoint `/report/export` using version `beta`?
Remove previous `beta` versions if you have someone.
```
image: "frankescobar/allure-docker-service:beta"
```
I will be waiting for your feedback.

**Comment by fescobar** [comment]
@karolxavierleite the new feature was re-released in version `2.13.1` (it's available as the latest)
https://github.com/fescobar/allure-docker-service#export-native-full-report
Remove previous `2.13.1` & `latest` versions if you had someone.

`image: "frankescobar/allure-docker-service"` .

Thank you for the suggestion.
