### ISSUE TITLE
Why files are sand and saved in format .bin ?

### ISSUE THREAD

**Issue by FullZero5** [fescobar/allure-docker-service#70]
Good day! Rewrote the script from[ Python](https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-api-usage/send_results.py) to Groovy, send reports to the server,
but attachments do not appear, if you upload them they are in .bin format. Tell me the pictures do not need to be encrypted when sending?
![image](https://user-images.githubusercontent.com/11909399/77302978-39c89e80-6d03-11ea-9eeb-ebce0bda9050.png)
![image](https://user-images.githubusercontent.com/11909399/77303124-709eb480-6d03-11ea-8a8a-f9ec7cadeef5.png)

``` java
task sendReports {
    group "Work Allure Server api"
    description "send results test in remote server"
    doLast {
        File f = new File("${project.buildDir}/allure-results");
        if (f.exists() && f.isDirectory()) {
            def request = new Request()
            f.eachFile {
                Reports files = new Reports(
                        file_name: it.name,
                        content_base64: it.text.bytes.encodeBase64()
                )
                request.results.add(files)
            }
            def req = new URL(gradle.allureServer+"/send-results").openConnection()
            req.setRequestMethod("POST")
            req.setRequestProperty("Content-Type", "application/json; charset=UTF-8")
            req.setDoOutput(true)
            req.getOutputStream().write(JsonOutput.toJson(request).getBytes("UTF-8"))
            logger.quiet "Status code: ${req.getResponseCode()}"
            def resp = new JsonSlurper().parseText(req.getInputStream().getText())
            logger.quiet "Response: ${resp}"
        } else {
            logger.quiet "Not folder: ${project.buildDir}/allure-results"
        }
    }
}

class Request {
    List<Reports> results = new LinkedList<>()
}
class Reports {
    String file_name
    String content_base64
}
```

**Comment by fescobar** [comment]
@FullZero5 can you try to send your results using this script? I'm not sure if you are encoding your images in the right way.
https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-api-usage/send_results.py
If the problem persists, can you send me some results to reproduce this?
Also, I wanted to know how did you get the image locally?
Thank you

**Comment by FullZero5** [comment]
Thanks for the answer, I wanted to use the python script, but I was not allowed to use it. I need to rewrite the code from python to groovy. I don’t understand how python script works. My code sends reports, but attachments do not send correctly.
1) I tried to use
https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-api-usage/send_results.py - everything works well. (problems with my code, I do not encode images correctly)
2) files [allure-results.zip](https://github.com/fescobar/allure-docker-service/files/4369510/allure-results.zip)
3) Locally, I just take the images from the folder ${myproject}/build/allure-results
![image](https://user-images.githubusercontent.com/11909399/77320362-7c00d880-6d21-11ea-961d-12b50768e9c5.png)

**Comment by fescobar** [comment]
@FullZero5 `${project.buildDir}/` this one only works in Jenkins, otherwise use `./allure-results`
Groovy is similar to Java. Try to open the file and converted as bytes after that, you can convert it to base64
```
byte[] fileContent = FileUtils.readFileToByteArray(new File(filePath));
String encodedString = Base64.getEncoder().encodeToString(fileContent);
```
https://www.baeldung.com/java-base64-image-string#convert-file

It's the only way I can help you. Good Luck.

**Comment by FullZero5** [comment]
Thank you very much 🆗

**Comment by FullZero5** [comment]
I'll add the code, it might come in handy for someone (it works somehow)
```java
task sendReports {
    group "Work Allure Server api"
    description "send results test in remote server"
    doLast {
        File f = new File("${project.buildDir}/allure-results")
        if (f.exists() && f.isDirectory()) {
            def request = new Request()
            f.eachFile {
                Reports files = new Reports(
                        file_name: it.name,
                        content_base64: it.bytes.encodeBase64()
                )
                request.results.add(files)
            }
            def req = new URL(gradle.allureServer+"/send-results").openConnection()
            req.setRequestMethod("POST")
            req.setRequestProperty("Content-Type", "application/json; charset=UTF-8")
            req.setDoOutput(true)
            req.getOutputStream().write(JsonOutput.toJson(request).getBytes("UTF-8"))
            logger.quiet "Status code: ${req.getResponseCode()}"
            def resp = new JsonSlurper().parseText(req.getInputStream().getText())
            logger.quiet "Response: ${resp}"
        } else {
            logger.quiet "Not folder: ${project.buildDir}/allure-results"
        }
    }
}

class Request {
    List<Reports> results = new LinkedList<>()
}
class Reports {
    String file_name
    String content_base64
}

```

**Comment by fescobar** [comment]
@FullZero5 I've added it a new example in case you use pipelines in Jenkins
https://github.com/fescobar/allure-docker-service/blob/master/allure-docker-api-usage/send_results_jenkins_pipeline.groovy
