### ISSUE TITLE
require templet for allure2-jbehave-maven-java

### ISSUE THREAD

**Issue by jadhavrahul10** [fescobar/allure-docker-service#73]
Hi team,

I am working on Allure reporting tool and i really like the tool and integration with this tool
I am looking template base on allure2-jbehave-maven-java.

Thanks

**Comment by fescobar** [comment]
@jadhavrahul10 this is not the right place to ask for that example, you have to do it here https://github.com/allure-framework/allure2
I could create an example in the future, but it's not my priority.
