### ISSUE TITLE
Add the ability to remove only one test from the report

### ISSUE THREAD

**Issue by imixac** [fescobar/allure-docker-service#76]
Hello

I did not find in the documentation the ability to delete one test. A lot of old and not relevant tests are piling up that I would like to get rid of.

**Comment by fescobar** [comment]
@imixac can you provide more details like screenshots? I don't understand why do you have old results, you can clean the results before generating the report again.

**Comment by imixac** [comment]
indeed, I can only delete run results. Thank

**Comment by fescobar** [comment]
@imixac let me see if it's possible and useful to add that feature. I'm doing some changes to improve the container. Thanks
