### ISSUE TITLE
Make executor counter customizable

### ISSUE THREAD

**Issue by IgorDodukh** [fescobar/allure-docker-service#83]
Hello,

In current implementation executor counter is updating automatically starting from #1
Can you, please, make an update to `/generate-report` request with new parameter like `?build_number={integer}`. 

Also make this number a part of the URL to the report:
`/projects/ui-test/reports/{build_number}/index.html`

In case of automatic report generation this number will be generated automatically, as it is in current version. But if generate report by API request - allow adding custom build number.

![executor00](https://user-images.githubusercontent.com/17238214/84301421-6b137680-ab5c-11ea-9e48-43730171d765.png)

It is useful in cases when we want to link a build number from CI/CD which triggered tests with the report version in Allure.

Thanks in advance.

**Comment by fescobar** [comment]
@IgorDodukh Instead of letting you pass a custom build number, it will be useful to return you the report URL generated? For example:

```
 {
  "data": {
    "report_url": "http://localhost:5050/projects/default/reports/1/index.html"
    "allure_results_files": [
      "result1.json",
      "executor.json"
    ]
  },
  "meta_data": {
    "message": "Report successfully generated for project_id 'default'"
  }
}
```
What do you think?

**Comment by IgorDodukh** [comment]
@fescobar Yes, I think it is a good idea. URL in response will be enough.

**Comment by fescobar** [comment]
@IgorDodukh I will add the feature on this ticket https://github.com/fescobar/allure-docker-service/issues/84
