### ISSUE TITLE
Fix log message: Server started at <http://172.31.0.11:4040/>. Press <Ctrl+C> to exit

### ISSUE THREAD

**Issue by dE1l** [fescobar/allure-docker-service#90]
But i can't open http://192.168.16.11:4040/
localhost:5050 will be correct

> allure_1                    | Not checking results automatically
> allure_1                    | ALLURE_VERSION: 2.13.3
> allure_1                    | Opening existing report
> allure_1                    | Cleaning results for PROJECT_ID: default
> allure_1                    | Starting web server...
> allure_1                    | Creating history on results directory for PROJECT_ID: default ...
> allure_1                    | Copying history from previous results...
> allure_1                    | Creating executor.json for PROJECT_ID: default
> allure_1                    | Generating report for PROJECT_ID: default
> allure_1                    | 2020-06-16 13:32:11.991:INFO::main: Logging initialized @4421ms to org.eclipse.jetty.util.log.StdErrLog
> allure_1                    | Can not open browser because this capability is not supported on your platform. You can use the link below to open the report manually.
> allure_1                    | Server started at <http://172.31.0.11:4040/>. Press <Ctrl+C> to exit
> allure_1                    | Report successfully generated to /app/allure-docker-api/static/projects/default/reports/latest
> allure_1                    | Status: 200

>   allure:
>     image: "frankescobar/allure-docker-service"
>     environment:
>       CHECK_RESULTS_EVERY_SECONDS: NONE
>       KEEP_HISTORY: "TRUE"
>       KEEP_HISTORY_LATEST: 20
>       SERVER_URL: "http://localhost:5050/latest-report"
>     volumes:
>       - ./allure-results:/app/allure-results
>       - ./allure-reports:/app/default-reports
>     ports:
>       - "5050:5050"
>       - "4040:4040"

**Comment by fescobar** [comment]
@dE1l Use port 5050. The port 4040 was deprecated. It's using 4040 and 5050 to avoid compatibility problems. Read the documentation and examples.

https://github.com/fescobar/allure-docker-service#port-4040-deprecated

**Comment by dE1l** [comment]
https://github.com/fescobar/allure-docker-service#port-4040-deprecated
i'm know it and i'm understand it.
I don't use 4040, but in logs i'm see:

> Server started at http://172.31.0.11:4040/. Press <Ctrl+C> to exit

it's issue about this **incorrect** message and i wrote about it in header.
I think you need reopen this issue and fix this bug.

**Comment by fescobar** [comment]
@dE1l Internally I use 4040 and 5050. The message is correct. But I will try to hide it to avoid confusions.

**Comment by fescobar** [comment]
@dE1l I've released version `2.13.4` with changes suggested. https://github.com/fescobar/allure-docker-service/releases/tag/v2.13.4

Thanks
