### ISSUE TITLE
 java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default/reports/latest

### ISSUE THREAD

**Issue by ankur1233** [fescobar/allure-docker-service#97]
I'm not able to run allure-docker. it's through  **java.nio.file.AccessDeniedException: /app/allure-docker-api/static/projects/default/reports/latest** this error when i check logs .

![image](https://user-images.githubusercontent.com/18676332/85834502-20773880-b7b1-11ea-83fa-8914ee3af325.png)

![image](https://user-images.githubusercontent.com/18676332/85834548-3684f900-b7b1-11ea-8931-0340e95854fc.png)

Can anyone please help me with this.

**Comment by fescobar** [comment]
@ankur1233 Surely you are mounting a directory with root permissions. Check this doc:

https://github.com/fescobar/allure-docker-service#override-user-container

**Comment by fescobar** [comment]
https://github.com/fescobar/allure-docker-service/issues/65

**Comment by syed1988** [comment]
Hello, I am getting permission denied error.
Here is the relevant portion of my docker-compose.yml file:
```
